// Code generated by xgo (XGo); DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goplus/dql/ts"
	"github.com/goplus/xgo/dql/reflects"
	"github.com/microsoft/typescript-go/ast"
	_ "github.com/qiniu/x/stream/zip"
)

const _ = true
//line demo/walke2b/walke2b.xgo:8
func main() {
//line demo/walke2b/walke2b.xgo:8:1
	doc := ts.Source("zip:index.d.ts.zip#index.d.ts")
	for
//line demo/walke2b/walke2b.xgo:10:1
	n := range ts.NodeSet_Cast(func(_xgo_yield func(reflects.Node) bool) {
//line demo/walke2b/walke2b.xgo:10:1
		doc.XGo_Elem("statements").XGo_Elem("nodes").XGo_Child().XGo_Enum()(func(self ts.NodeSet) bool {
//line demo/walke2b/walke2b.xgo:10:1
			if self.XGo_Attr__0("kind") == ast.KindInterfaceDeclaration {
//line demo/walke2b/walke2b.xgo:10:1
				if
//line demo/walke2b/walke2b.xgo:10:1
				_xgo_val, _xgo_err := self.XGo_first(); _xgo_err == nil {
//line demo/walke2b/walke2b.xgo:10:1
					if !_xgo_yield(_xgo_val) {
//line demo/walke2b/walke2b.xgo:10:1
						return false
					}
				}
			}
//line demo/walke2b/walke2b.xgo:10:1
			return true
		})
	}).XGo_Enum() {
//line demo/walke2b/walke2b.xgo:11:1
		decl := n.XGo_Elem("asInterfaceDeclaration")
//line demo/walke2b/walke2b.xgo:12:1
		if decl.XGo_Attr__0("name") == "paths" {
			for
//line demo/walke2b/walke2b.xgo:13:1
			m := range decl.XGo_Elem("members").XGo_Elem("nodes").XGo_Child().XGo_Enum() {
//line demo/walke2b/walke2b.xgo:14:1
				fmt.Println("==>", m.XGo_Attr__0("kind"))
			}
		}
	}
}
